In [1]:
import numpy as np

In [2]:
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr+ arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [7]:
arr / arr

C:\Users\kirui\AppData\Local\Temp\ipykernel_15908\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [8]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
arr ** 4

array([   0,    1,   16,   81,  256,  625, 1296, 2401, 4096, 6561],
      dtype=int32)

In [10]:
np.log(arr)

C:\Users\kirui\AppData\Local\Temp\ipykernel_15908\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [11]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [13]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [15]:
arrdec = np.random.randn(10)*5
arrdec

array([ -3.84826946,  -5.14421677,   6.64256386,  -0.60505305,
        -5.79147863,   9.42426921,   4.86978844,  -1.72146387,
       -13.2303151 ,  -4.71380271])

In [16]:
np.ceil(arrdec)

array([ -3.,  -5.,   7.,  -0.,  -5.,  10.,   5.,  -1., -13.,  -4.])

In [17]:
np.floor(arrdec)

array([ -4.,  -6.,   6.,  -1.,  -6.,   9.,   4.,  -2., -14.,  -5.])

In [18]:
np.trunc(arrdec)

array([ -3.,  -5.,   6.,  -0.,  -5.,   9.,   4.,  -1., -13.,  -4.])

In [19]:
np.absolute(arrdec)

array([ 3.84826946,  5.14421677,  6.64256386,  0.60505305,  5.79147863,
        9.42426921,  4.86978844,  1.72146387, 13.2303151 ,  4.71380271])