In [1]:
import numpy as np

In [2]:
array = np.arange(10)

In [3]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
array(0)

TypeError: 'numpy.ndarray' object is not callable

In [5]:
array[0]

0

## array[0:4]

In [7]:
array2 = np.array(([2,3,4,5],[3,4,5,6],[4,5,6,7]))

In [8]:
array2

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [9]:
array2[0]

array([2, 3, 4, 5])

In [10]:
array2[0][0]

2

In [11]:
array2[1:, 1:]

array([[4, 5, 6],
       [5, 6, 7]])

In [12]:
array2(:2, :2)

SyntaxError: invalid syntax (2030490855.py, line 1)

In [13]:
array2[:2, :2]

array([[2, 3],
       [3, 4]])

In [14]:
array[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr = np.arange(10)

In [17]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
portion =arr[5:]

In [20]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
portion

array([5, 6, 7, 8, 9])

In [22]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arrc = arr.copy()

In [25]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
portion[:] = 1

In [27]:
portion

array([1, 1, 1, 1, 1])

In [28]:
arr

array([0, 1, 2, 3, 4, 1, 1, 1, 1, 1])

In [29]:
arrc = arr.copy()

In [30]:
arr

array([0, 1, 2, 3, 4, 1, 1, 1, 1, 1])

In [31]:
arr>1

array([False, False,  True,  True,  True, False, False, False, False,
       False])

In [32]:
arr[arr>1]

array([2, 3, 4])