In [1]:
import numpy as np

In [2]:
arr = np.array([10,20,30])

In [4]:
print(arr)

[10 20 30]


In [5]:
mat = np.array([[2,3,4],[5,6,7],[8,9,10]])

In [6]:
mat

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [9]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.eye(5)#identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
np.arrange(10)

AttributeError: module 'numpy' has no attribute 'arrange'

In [12]:
ar = np.arange(10)

In [13]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
ar1 = np.arange(5,20)

In [15]:
ar1


array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
ar2 = np.arange(5,20,4)

In [17]:
ar2

array([ 5,  9, 13, 17])

In [18]:
ar.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
ar.reshape

<function ndarray.reshape>

In [20]:
ar.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [21]:
ar.reshape(2,5).shape

(2, 5)

In [22]:
ar.reshape(1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [23]:
ar.reshape(10,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [24]:
ar.max()

9

In [25]:
ar.argmax()

9

In [26]:
ar.min()

0

In [27]:
ar.argmax()

9

In [28]:
np.random.randint(5,20)

17

In [29]:
np.random.randint(5,20,3)

array([11,  9, 12])

In [30]:
np.random.rand(5)

array([0.70127328, 0.66378712, 0.98134408, 0.78940573, 0.96455486])

In [31]:
np.random.rand(5)

array([0.94239855, 0.35048712, 0.59272343, 0.96765237, 0.4934854 ])

In [32]:
np.random.rand(3,3)

array([[0.90947794, 0.59751832, 0.22676302],
       [0.48001325, 0.05630739, 0.40274364],
       [0.60719049, 0.41248622, 0.68118706]])

In [33]:
np.random.randn(5)

array([ 0.53497847, -0.92199289,  0.26778207,  0.65213284,  0.34632727])

In [ ]:
np.random.randn(5) 